#!/usr/bin/env python3
"""Build a self-contained HTML playbook from companies_by_pain.csv (no secrets)."""
import csv, os, html
ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
def p(*a): return os.path.join(ROOT, *a)
rows = list(csv.DictReader(open(p("output", "companies_by_pain.csv"), encoding="utf-8")))
TOP = rows[:60]
n = len(rows)
with_email = sum(1 for r in rows if r["dm_email"])
with_phone = sum(1 for r in rows if r["dm_phone"])
no_cto = sum(1 for r in rows if r["has_full_time_cto"] == "no")

def td(s): return f"<td>{html.escape(str(s))}</td>"
trs = []
for r in TOP:
    trs.append("<tr>" + "".join([
        td(r["rank"]), td(r["pain_score"]),
        f"<td><b>{html.escape(r['company'])}</b><br><span class=dim>{html.escape(r['industry'][:30])}</span></td>",
        td(r["integration_opportunity"]),
        f"<td>{'<span class=red>none</span>' if r['has_full_time_cto']=='no' else 'has CTO'}<br><span class=dim>{html.escape(str(r['technical_ratio']))} tech ratio</span></td>",
        f"<td>{html.escape(r['decision_maker'])}<br><span class=dim>{html.escape(r['dm_title'][:24])}</span></td>",
        f"<td>{html.escape(r['dm_phone'])}<br><span class=dim>{html.escape(r['dm_email'][:30])}</span></td>",
        f"<td class=op>{html.escape(r['opener'])}</td>",
    ]) + "</tr>")

HTML = f"""<!doctype html><html><head><meta charset=utf-8>
<meta name=viewport content="width=device-width,initial-scale=1">
<title>Carl Maloney — Integration-Gap Lead List</title>
<style>
body{{background:#0d1117;color:#e6edf3;font:15px/1.5 -apple-system,Segoe UI,Roboto,sans-serif;margin:0;padding:24px}}
h1{{font-size:24px;margin:0 0 4px}} .sub{{color:#7d8590;margin-bottom:20px}}
.stats{{display:flex;gap:16px;flex-wrap:wrap;margin-bottom:24px}}
.stat{{background:#161b22;border:1px solid #30363d;border-radius:10px;padding:14px 18px;min-width:120px}}
.stat b{{font-size:26px;display:block;color:#58a6ff}}
table{{border-collapse:collapse;width:100%;font-size:13px}}
th,td{{border-bottom:1px solid #21262d;padding:8px 10px;text-align:left;vertical-align:top}}
th{{color:#7d8590;position:sticky;top:0;background:#0d1117}}
.dim{{color:#7d8590;font-size:11px}} .red{{color:#f85149;font-weight:600}}
.op{{max-width:340px;color:#adbac7;font-size:12px}}
tr:hover{{background:#161b22}}
</style></head><body>
<h1>Carl Maloney — Series A Integration-Gap Lead List</h1>
<div class=sub>Companies missing a business-critical integration · thin on technical leadership · sorted by pain. Built with Blueprint GTM.</div>
<div class=stats>
<div class=stat><b>{n}</b>qualified companies</div>
<div class=stat><b>{no_cto}</b>no full-time CTO</div>
<div class=stat><b>{with_phone}</b>with phone</div>
<div class=stat><b>{with_email}</b>with email</div>
</div>
<h2>Top 60 by pain</h2>
<table><thead><tr>
<th>#</th><th>Pain</th><th>Company</th><th>Integration opportunity</th><th>Tech leadership</th>
<th>Decision-maker</th><th>Contact</th><th>Opener (message = redescription of targeting)</th>
</tr></thead><tbody>
{''.join(trs)}
</tbody></table>
<p class=dim>Full list: companies_by_pain.csv ({n} rows) + people.csv. Generated by the CTOx prospecting pipeline.</p>
</body></html>"""
out = p("output", "carl_leads_playbook.html")
open(out, "w", encoding="utf-8").write(HTML)
print("wrote", out, f"({len(HTML)} bytes, {len(TOP)} rows shown of {n})")
